name: 'ABLUnit Results'
description: 'A parser for results.xml'
inputs:
  file:
    description: 'The file to parse'
    default: 'result.xml'
outputs:
  test-ok:
    description: 'Test OK? true if all tests are executed with a positive result'
runs:
  using: 'node16'
  main: 'dist/index.js'
