name: 'ABLUnit Results'
description: 'A parser for results.xml'
inputs:
  file:
    description: 'The file to parse'
    default: 'result.xml'
  errors-only:
    description: 'Only show errors?'
    default: 'true'
  fail-on-error:
    description: 'Fail on error?'
    default: 'true'
  debug:
    description: 'Debug?'
    default: 'false'
outputs:
  test-ok:
    description: 'Test OK? true if all tests are executed with a positive result'
runs:
  using: 'node20'
  main: 'dist/index.js'
