name: test-action

on:
  push

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8         # v3.1.0
        with:
          path: .

      - name: Check unit tests
        uses: bfv/ablunit-results@master
        with:
          file: ./results.xml
      
